In [1]:
list1 = [1,2,3]
list2 = ["zl","plj","wd",22,True]
list3 = [list1,list2,[]]

In [5]:
print(list3)

[[1, 2, 3], ['zl', 'plj', 'wd', 22, True], []]


In [2]:
import numpy as np

In [6]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [7]:
type(x) 

numpy.ndarray

In [8]:
x.ndim #w维度

1

In [9]:
x.shape

(4,)

In [10]:
x.size

4

In [12]:
x.itemsize

4

In [13]:
x.data

In [17]:
y=np.array([[1,2,3,4],[6,7,8,9],[2,3,6,8]])
y

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [2, 3, 6, 8]])

In [19]:
y.ndim

2

In [20]:
y.size

12

In [24]:
size_y=y.shape
size_y

(3, 4)

In [26]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.array(range(0,10,2))

array([0, 2, 4, 6, 8])

In [32]:
np.array(range(10,0,-2))

array([10,  8,  6,  4,  2])

In [36]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.ones([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.25288368e-321],
       [1.97345609e-312, 1.42410974e-306, 2.56761491e-312]])

In [44]:
np.random.randint?