In [1]:
import numpy as np

In [2]:
a=np.arange(0,16).reshape(4,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
a.sum()

120

In [6]:
a.mean()

7.5

In [10]:
a.var()

21.25

In [11]:
a.prod()

0

In [12]:
a.cumsum()   #累加

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120], dtype=int32)

In [13]:
a.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [14]:
a<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [19]:
a<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
(a<5).any()

True

In [18]:
(a<5).all()

False