In [1]:
import numpy as np
#x[start end step]

In [71]:
x=np.array([ 1,2,3,4,5,6,7,8,9,10])

In [5]:
x>=2

array([False,  True,  True,  True,  True,  True,  True])

In [10]:
(x<4) | (x>7)

array([ True,  True,  True, False, False, False, False,  True,  True,
        True])

In [8]:
(x<4) & (x>7)

array([False, False, False, False, False, False, False])

In [14]:
x[x<4]

array([1, 2, 3])

In [16]:
x[(x<=2)|(x>7)]

array([ 1,  2,  8,  9, 10])

In [17]:
x.sum()

55

In [20]:
np.sum(x<9)

8

In [26]:
np.where(x==3)

(array([2], dtype=int64),)

In [27]:
np.pi

3.141592653589793

In [28]:
x[2:5]

array([3, 4, 5])

In [29]:
x[::2]  #::表示取所有数字，步长为2

array([1, 3, 5, 7, 9])

In [30]:
x[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [31]:
x[:6]

array([1, 2, 3, 4, 5, 6])

In [32]:
x[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
x[::]   #::表示所有

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
y[::,::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
y[0,::]

array([1, 2, 3, 4])

In [56]:
z=np.ones([3,4])
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
z[1:,::]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
y[1:,::]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
y1=np.arange(0,16).reshape(4,4)
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
t1=np.arange(0,16)
z1=t1.reshape(4,4)
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.arange(0,5)  #左闭右开区间

array([0, 1, 2, 3, 4])

In [75]:
yz=[y1,z1]
yz

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [76]:
z1.ravel()  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
z1.flatten() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [87]:
yzh=np.hstack([y1,z1])  #水平合并
yz

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])

In [88]:
yzh=np.vstack([y1,z1])  #垂直合并
yzh

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
yzd=np.dstack([y1,z1])  
yzd

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  2],
        [ 3,  3]],

       [[ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7]],

       [[ 8,  8],
        [ 9,  9],
        [10, 10],
        [11, 11]],

       [[12, 12],
        [13, 13],
        [14, 14],
        [15, 15]]])

In [91]:
yzc_v=np.concatenate([y1,z1],axis=0)  
yzc_v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
yzc_h=np.concatenate([y1,z1],axis=1)  
yzc_h

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])